CREATE TABLE BOARD(  
    NUM INT NOT NULL AUTO_INCREMENT,  
    NAME VARCHAR(100) NOT NULL,  
    PWD VARCHAR(100) NOT NULL,  
    EMAIL VARCHAR(100) NOT NULL,  
    SUBJECT VARCHAR(100) NOT NULL,  
    CONTENT VARCHAR(100) NOT NULL,  
    IPADDR VARCHAR(100) NOT NULL,  
    HITCOUNT VARCHAR(100) NOT NULL,  
    CREATED VARCHAR(100) NOT NULL,  	 	 	 	 	     
    PRIMARY KEY ( NUM )
)
